name = "memoflow-backend"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "memoflow-super-secret-key"

[[kv_namespaces]]
binding = "KV"
id = "memoflow_kv_placeholder"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "memoflow-bucket-placeholder"

[[d1_databases]]
binding = "DB"
database_name = "memoflow-db"
database_id = "memoflow_db_placeholder"
